"""empty message

Revision ID: 22a06f4163c4
Revises: 
Create Date: 2020-04-14 19:28:59.211906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a06f4163c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('clients_id', sa.Integer(), nullable=False),
    sa.Column('clients_username', sa.String(length=30), nullable=False),
    sa.Column('clients_email', sa.String(length=100), nullable=True),
    sa.Column('clients_password', sa.String(length=100), nullable=True),
    sa.Column('clients_phone', sa.Integer(), nullable=True),
    sa.Column('clients_rut', sa.String(length=30), nullable=True),
    sa.Column('clients_address', sa.String(length=80), nullable=True),
    sa.Column('clients_profession', sa.String(length=30), nullable=True),
    sa.Column('clients_nationality', sa.String(length=30), nullable=True),
    sa.Column('clients_civil_status', sa.String(length=20), nullable=True),
    sa.Column('clients_avatar', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('clients_id'),
    sa.UniqueConstraint('clients_address'),
    sa.UniqueConstraint('clients_avatar'),
    sa.UniqueConstraint('clients_email'),
    sa.UniqueConstraint('clients_phone'),
    sa.UniqueConstraint('clients_rut'),
    sa.UniqueConstraint('clients_username')
    )
    op.create_table('lawyers',
    sa.Column('lawyers_id', sa.Integer(), nullable=False),
    sa.Column('lawyers_name', sa.String(length=30), nullable=False),
    sa.Column('lawyers_field', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('lawyers_id'),
    sa.UniqueConstraint('lawyers_field'),
    sa.UniqueConstraint('lawyers_name')
    )
    op.create_table('rols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cases',
    sa.Column('cases_id', sa.Integer(), nullable=False),
    sa.Column('cases_matter', sa.String(length=20), nullable=False),
    sa.Column('cases_date', sa.DateTime(), nullable=False),
    sa.Column('cases_description', sa.Text(length=300), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.clients_id'], ),
    sa.PrimaryKeyConstraint('cases_id')
    )
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('users_name', sa.String(length=30), nullable=False),
    sa.Column('users_issue_subject', sa.String(length=30), nullable=False),
    sa.Column('users_issue_description', sa.Text(length=3000), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.lawyers_id'], ),
    sa.PrimaryKeyConstraint('users_id')
    )
    op.create_table('documents',
    sa.Column('documents_id', sa.Integer(), nullable=False),
    sa.Column('documents_files', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.cases_id'], ),
    sa.PrimaryKeyConstraint('documents_id')
    )
    op.create_table('lawyer_case',
    sa.Column('lawyers_id', sa.Integer(), nullable=False),
    sa.Column('cases_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cases_id'], ['cases.cases_id'], ),
    sa.ForeignKeyConstraint(['lawyers_id'], ['lawyers.lawyers_id'], ),
    sa.PrimaryKeyConstraint('lawyers_id', 'cases_id')
    )
    op.create_table('messages',
    sa.Column('messages_id', sa.Integer(), nullable=False),
    sa.Column('messages_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('messages_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('lawyer_case')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('cases')
    op.drop_table('rols')
    op.drop_table('lawyers')
    op.drop_table('clients')
    # ### end Alembic commands ###
