"""empty message

Revision ID: 2942b0f1c98e
Revises: 503744255dbe
Create Date: 2020-04-14 19:49:17.230798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2942b0f1c98e'
down_revision = '503744255dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'documents_files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('documents_files', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
