"""empty message

Revision ID: 503744255dbe
Revises: 22a06f4163c4
Create Date: 2020-04-14 19:47:27.382199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503744255dbe'
down_revision = '22a06f4163c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('documents_files', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'documents_files')
    # ### end Alembic commands ###
