"""empty message

Revision ID: 8251b1a7e859
Revises: 2942b0f1c98e
Create Date: 2020-04-23 20:22:18.213034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8251b1a7e859'
down_revision = '2942b0f1c98e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'clients_password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_index('clients_address', table_name='clients')
    op.drop_index('clients_avatar', table_name='clients')
    op.add_column('lawyers', sa.Column('lawyers_email', sa.String(length=100), nullable=True))
    op.add_column('lawyers', sa.Column('lawyers_file_speciality', sa.Integer(), nullable=True))
    op.add_column('lawyers', sa.Column('lawyers_password', sa.String(length=30), nullable=False))
    op.add_column('lawyers', sa.Column('lawyers_phone', sa.Integer(), nullable=True))
    op.add_column('lawyers', sa.Column('lawyers_rut', sa.String(length=30), nullable=False))
    op.add_column('lawyers', sa.Column('lawyers_title', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'lawyers', ['lawyers_phone'])
    op.create_unique_constraint(None, 'lawyers', ['lawyers_email'])
    op.create_unique_constraint(None, 'lawyers', ['lawyers_rut'])
    op.add_column('messages', sa.Column('messages_content', sa.String(length=20000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'messages_content')
    op.drop_constraint(None, 'lawyers', type_='unique')
    op.drop_constraint(None, 'lawyers', type_='unique')
    op.drop_constraint(None, 'lawyers', type_='unique')
    op.drop_column('lawyers', 'lawyers_title')
    op.drop_column('lawyers', 'lawyers_rut')
    op.drop_column('lawyers', 'lawyers_phone')
    op.drop_column('lawyers', 'lawyers_password')
    op.drop_column('lawyers', 'lawyers_file_speciality')
    op.drop_column('lawyers', 'lawyers_email')
    op.create_index('clients_avatar', 'clients', ['clients_avatar'], unique=True)
    op.create_index('clients_address', 'clients', ['clients_address'], unique=True)
    op.alter_column('clients', 'clients_password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
