"""empty message

Revision ID: a1ef89242151
Revises: e568fed3c030
Create Date: 2020-05-17 14:41:31.994264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1ef89242151'
down_revision = 'e568fed3c030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'messages_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'messages_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
