"""empty message

Revision ID: dfba29c92a8f
Revises: 8251b1a7e859
Create Date: 2020-04-27 12:32:44.410956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfba29c92a8f'
down_revision = '8251b1a7e859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('messages_content', sa.Text(length=20000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'messages_content')
    # ### end Alembic commands ###
