"""empty message

Revision ID: e568fed3c030
Revises: dfba29c92a8f
Create Date: 2020-05-17 14:19:51.658123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e568fed3c030'
down_revision = 'dfba29c92a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyers', sa.Column('lawyers_account', sa.String(length=15), nullable=False))
    op.add_column('lawyers', sa.Column('lawyers_bank', sa.String(length=30), nullable=False))
    op.add_column('lawyers', sa.Column('lawyers_bank_number', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'lawyers', ['lawyers_bank_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lawyers', type_='unique')
    op.drop_column('lawyers', 'lawyers_bank_number')
    op.drop_column('lawyers', 'lawyers_bank')
    op.drop_column('lawyers', 'lawyers_account')
    # ### end Alembic commands ###
